### ISSUE TITLE
Create `go` template

### ISSUE THREAD

**Issue by shiipou** [lenra-io/template-go#1]
Template must run the counter app in [Go](https://github.com/golang/go)

We choose to use the same app for each template to help new developers to see how to implement they app when switching languages.

## Tasks to do:

Setting up the default app:
- [ ] Create `handle_manifest` function
- [ ] Create `handle_widget` function
- [ ] Create `handle_listener` function
- [ ] Create `handle_resource` function
- [ ] Create `get_document` function
- [ ] Create `create_document` function
- [ ] Create `update_document` function
- [ ] Create `delete_document` function
- [ ] Create `execute_query` function

Setting up widgets:
- [ ] root
- [ ] home
- [ ] menu
- [ ] counter
- [ ] loading
- [ ] root

Setting up listeners:
- [ ] onEnvStart
- [ ] onUserFirstJoin
- [ ] increment

## Config lenra with Dofigen
- [ ] Add `/lenra.yml` Dofigen file for template configuration
